### PR TITLE
Delete is working!

### PR DESCRIPTION
**Pull request by pauldowlin**
Delete is now working on a per item bases and in bulk.  I added visual clues as to how many total items verses how many are available on screen, a 'check all' option and brought back the media-options popup.  I opted to not show small preview of selected items in favor of a cleaner look of just # of selected items and actions to be taken on them.  I left the tag icon in there but there is no functionality to it .  I'm hoping I can tap into Media Tags bulk tagging functions and display their popup that tags selected items in bulk.

### CODE REVIEW

**Comment by helen** [comment]
This looks like a lot of changes, not all of them related to deleting media items. Checking with @shaunandrews about the differences between this and the .org repo. In the future and in general, not just for this project, pull requests should be self-contained and address the issue at hand.

**Comment by pauldowlin** [comment]
Hi Helen
Love the plugin and am very excited to help with the project.  Maybe some
of the confusion is based on my inexperience with Github and the fact that
the code on Github is old compared to what is on wordpress.org (thought I
made that clear on my first commit).  Can you not see my individual
commits?   When I read thru the Github documentation it talked about making
commits than when ready sending a pull request.

Maybe I am confused on this and it might help if you could explain in more
detail how this should have been parceled out to stay within scope.
 Because honestly, I thought everything was within scope of getting delete
to work with the plugin.

Just trying to help :-)
Paul

**Comment by helen** [comment]
No worries - I appreciate the enthusiasm and help, for sure. I just tend toward being terse/brief a lot of the time, which doesn't always come across well.

So, I think what I'm trying to say is that pull requests, much like commits, are better served when they do what they say they do, no more, no less. This helps with tracing the history of the project. With GitHub, the pull request is separate from the commits, but it's also a part of the history.

In this case, if you'd like to try your hand at it, I think a separate pull request for updating to match what's on .org would be appropriate. I actually had no idea the two had diverged. Then, from there, we can do another pull request for what exactly is related to deleting (or re-use this one, although I have to admit that I don't really know what's involved in changing a pull request) - a separate pull request for that also makes it easier for me to see what those code changes are specifically.

**Comment by pauldowlin** [comment]
I will try to 'close' the commit. And then resubmit pull requests for updating to what's on .org than again for just delete.

Let me know if that works.

:-)

**Pull request closed without merging**
